/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DownloadXRViewerLayout: typeof import('./src/components/projects/ar/pages/DownloadXRViewerLayout.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    ProjectCard: typeof import('./src/components/ui/ProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThreeAR: typeof import('./src/components/projects/ar/threejs/ThreeAR.vue')['default']
  }
}
